# Generated by Django 5.2.9 on 2025-12-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_review'),
        ('patient', '0003_patient_address_patient_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('has_icu', models.BooleanField(default=True, help_text='Has ICU facility')),
                ('has_operation_theater', models.BooleanField(default=True)),
                ('is_24x7', models.BooleanField(default=True)),
                ('facilities', models.TextField(help_text='Available facilities and equipment')),
            ],
            options={
                'verbose_name': 'Burn Unit',
                'verbose_name_plural': 'Burn Units',
            },
        ),
        migrations.CreateModel(
            name='BurnDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='Burn treatment specialization', max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('certifications', models.TextField(help_text='Relevant certifications')),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burn_specialist', to='doctor.doctor')),
            ],
            options={
                'verbose_name': 'Burn Doctor',
                'verbose_name_plural': 'Burn Doctors',
            },
        ),
        migrations.CreateModel(
            name='BurnPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burn_severity', models.CharField(choices=[('First Degree', 'First Degree (Minor)'), ('Second Degree', 'Second Degree (Moderate)'), ('Third Degree', 'Third Degree (Severe)'), ('Fourth Degree', 'Fourth Degree (Critical)')], max_length=20)),
                ('affected_area_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of body affected', max_digits=5)),
                ('burn_location', models.TextField(help_text='Description of burn location on body')),
                ('cause_of_burn', models.TextField(help_text='How the burn occurred')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Under Treatment', 'Under Treatment'), ('Recovering', 'Recovering'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='burn_unit.burndoctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_cases', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Burn Patient',
                'verbose_name_plural': 'Burn Patients',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='BurnTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('treatment_type', models.CharField(help_text='Type of treatment (e.g., Skin Graft, Dressing, etc.)', max_length=200)),
                ('medications', models.TextField(help_text='Medications administered')),
                ('notes', models.TextField(help_text='Treatment notes and observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('burn_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='burn_unit.burnpatient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='burn_unit.burndoctor')),
            ],
            options={
                'verbose_name': 'Burn Treatment',
                'verbose_name_plural': 'Burn Treatments',
                'ordering': ['-treatment_date'],
            },
        ),
    ]
