# Generated by Django 5.2.9 on 2025-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='emergency_type',
            field=models.CharField(choices=[('Medical Emergency', 'Medical Emergency'), ('Accident', 'Accident'), ('Heart Attack', 'Heart Attack'), ('Stroke', 'Stroke'), ('Respiratory Distress', 'Respiratory Distress'), ('Other', 'Other')], max_length=30),
        ),
    ]
