# Generated by Django 5.2.9 on 2025-12-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_patient_address_patient_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('disease_prevented', models.CharField(help_text='Disease(s) this vaccine prevents', max_length=200)),
                ('age_group', models.CharField(choices=[('Infant', 'Infant (0-2 years)'), ('Child', 'Child (2-12 years)'), ('Teenager', 'Teenager (13-18 years)'), ('Adult', 'Adult (18-60 years)'), ('Senior', 'Senior (60+ years)'), ('All', 'All Ages')], max_length=20)),
                ('total_doses', models.IntegerField(default=1, help_text='Total number of doses required')),
                ('dose_interval_days', models.IntegerField(blank=True, help_text='Days between doses', null=True)),
                ('side_effects', models.TextField(blank=True, help_text='Common side effects')),
                ('precautions', models.TextField(blank=True, help_text='Precautions before taking')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.IntegerField(default=1, help_text='Which dose number (1, 2, 3, etc.)')),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=15)),
                ('administered_by', models.CharField(blank=True, help_text='Doctor/Nurse who administered', max_length=200)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch number', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or reactions')),
                ('next_dose_date', models.DateField(blank=True, help_text='Next dose scheduled date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patient.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vaccine.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Schedule name (e.g., 'India Immunization Schedule')", max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('Infant', 'Infant (0-2 years)'), ('Child', 'Child (2-12 years)'), ('Teenager', 'Teenager (13-18 years)'), ('Adult', 'Adult (18-60 years)'), ('Senior', 'Senior (60+ years)'), ('All', 'All Ages')], max_length=20)),
                ('is_recommended', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccines', models.ManyToManyField(related_name='schedules', to='vaccine.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccine Schedule',
                'verbose_name_plural': 'Vaccine Schedules',
            },
        ),
    ]
